import esbuild from "esbuild";
import process from "process";
import builtins from "builtin-modules";
import { readFile, stat, writeFile } from "node:fs/promises";
import { runtimeDeployPlugin } from "../deploy-runtime.mjs";

const banner =
	`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = (process.argv[2] === "production");

const syncStylesheet = {
	name: "sync-stylesheet",
	setup(build) {
		build.onEnd(async (result) => {
			if (result.errors.length > 0) return;
			try {
				await stat("main.css");
				await stat("styles-ui.css");
				const [calendarStyles, sharedUiStyles] = await Promise.all([
					readFile("main.css", "utf8"),
					readFile("styles-ui.css", "utf8"),
				]);
				await writeFile(
					"styles.css",
					`${calendarStyles.trimEnd()}\n\n/* BRAT-compatible bundled UI styles. */\n${sharedUiStyles.trimStart()}`,
					"utf8",
				);
			} catch (error) {
				console.warn("[tps-calendar-base] Failed to build the standard styles.css bundle", error);
			}
		});
	},
};

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ["src/main.ts"],
	bundle: true,
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtins],
	format: "cjs",
	target: "es2018",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	outfile: "main.js",
	minify: prod,
	plugins: [syncStylesheet, runtimeDeployPlugin("TPS-Calendar-Base (Dev)")],
});

if (prod) {
	await context.rebuild();
	process.exit(0);
} else {
	await context.watch();
}
