import fs from "fs";
import path from "path";
import { fileURLToPath } from "url";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const rootDir = path.resolve(__dirname, "..");
const buildDir = path.join(rootDir, "TPS-Calendar-Base");

// Ensure build directory exists
if (!fs.existsSync(buildDir)) {
  fs.mkdirSync(buildDir, { recursive: true });
}

const assets = ["main.js", "manifest.json", "styles.css"];

for (const asset of assets) {
  const srcInBuild = path.join(buildDir, asset);
  const destInRoot = path.join(rootDir, asset);
  const srcInRoot = path.join(rootDir, asset);
  const destInBuild = path.join(buildDir, asset);

  // If file exists in root but not in build (or we want to update build), copy to build
  // Note: main.js is generated by esbuild into buildDir, so we don't overwrite it from root unless intended.
  // But typically we want to copy static assets (manifest, styles) from root to build.
  
  if (asset === "main.js") {
      // main.js is built into buildDir, so we copy it to root for dev convenience if needed,
      // but the user specifically asked for the folder to be ready for copy-paste.
      if (fs.existsSync(srcInBuild)) {
          fs.copyFileSync(srcInBuild, destInRoot);
          console.log(`✓ Copied ${asset} from build to root`);
      }
  } else {
      // For other assets (manifest, styles), source of truth is root
      if (fs.existsSync(srcInRoot)) {
          fs.copyFileSync(srcInRoot, destInBuild);
          console.log(`✓ Copied ${asset} from root to build`);
      }
  }
}

console.log(`\n✅ Plugin files prepared in '${buildDir}' for distribution.`);